<a href="https://colab.research.google.com/github/chenboju/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import numpy as np

# 創建一個二維 NumPy 數組
arr = np.array([[1, 2, 3], [2, 3, 4]])

# 輸出數組
print(arr)

# 輸出數組的維度數量
print('number of dim', arr.ndim)

# 輸出數組的形狀（每個維度的大小）
print('shape', arr.shape)

# 輸出數組中元素的總數
print('size', arr.size)


[[1 2 3]
 [2 3 4]]
number of dim 2
shape (2, 3)
size 6


In [3]:
import numpy as np

# 創建一個 NumPy 數組，指定數據類型為32位整數
a = np.array([2, 34, 6, 7, 8], dtype=np.int32)
print(a)
# 輸出數組的數據類型
print(a.dtype)

# 創建一個 NumPy 數組，指定數據類型為64位浮點數
a = np.array([2, 34, 6, 7, 8], dtype=np.float64)
print(a)
# 輸出數組的數據類型
print(a.dtype)
print("\n")

# 創建一個二維 NumPy 數組
b = np.array([[2, 3, 4, 5], [5, 6, 7, 8]])
print(b)
print("\n")

# 創建一個三行四列的零矩陣
c = np.zeros((3, 4))
print(c)
print("\n")

# 創建一個三行四列的元素全為1的矩陣，指定數據類型為16位整數
d = np.ones((3, 4), dtype=np.int16)
print(d)
print("\n")

# 創建一個從2開始，以步長5生成的一維數組
e = np.arange(2, 50, 5)
print(e)
print("\n")

# 創建一個從0到11的數組，並將其形狀改為三行四列
e = np.arange(12).reshape((3, 4))
print(e)

# 生成一個從1到10的等差序列，共包含5個數字
f = np.linspace(1, 10, 5)
print(f)

# 生成一個從1到20的等差序列，共包含10個數字，並將其形狀改為兩行五列
f = np.linspace(1, 20, 10).reshape((2, 5))
print(f)


[ 2 34  6  7  8]
int32
[ 2. 34.  6.  7.  8.]
float64


[[2 3 4 5]
 [5 6 7 8]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[ 2  7 12 17 22 27 32 37 42 47]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.    3.25  5.5   7.75 10.  ]
[[ 1.          3.11111111  5.22222222  7.33333333  9.44444444]
 [11.55555556 13.66666667 15.77777778 17.88888889 20.        ]]


In [4]:
import numpy as np

# 創建一維數組 a 和一維數組 b
a = np.array([10, 20, 30, 40])
b = np.arange(4)

# 輸出數組 a 和數組 b
print(a, b)

# 對應元素相減
c = a - b
print(c)

# 對應元素的指數運算
c = a ** b
print(c)

# 對數組 a 中的每個元素進行 sin 運算，並乘以 10
c = 10 * np.sin(a)
print(c)

# 輸出數組 b、滿足條件的布林數組（b<3 和 b==3）
print(b, b < 3, b == 3)

# 創建二維數組 a 和二維數組 b
a = np.array([[1, 1], [0, 1]])
b = np.arange(4).reshape((2, 2))

# 輸出數組 a 和數組 b
print(a)
print("\n")
print(b)
print("\n")

# 對應元素相乘
c = a * b
# 矩陣乘法
c_dot = np.dot(a, b)
print(c)
print("\n")
print(c_dot)

# 創建一個形狀為 (2, 4) 的隨機數組
a = np.random.random((2, 4))

# 輸出數組 a、按行求和、按列求最小值、全局求最大值
print(a)
print(np.sum(a, axis=1)) #axis=1，按行
print(np.min(a, axis=0))  #axis=0，按列
print(np.max(a))


[10 20 30 40] [0 1 2 3]
[10 19 28 37]
[    1    20   900 64000]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[0 1 2 3] [ True  True  True False] [False False False  True]
[[1 1]
 [0 1]]


[[0 1]
 [2 3]]


[[0 1]
 [0 3]]


[[2 4]
 [2 3]]
[[0.13139141 0.74371292 0.81326735 0.48024971]
 [0.4185463  0.28903715 0.44769284 0.85672057]]
[2.16862138 2.01199686]
[0.13139141 0.28903715 0.44769284 0.48024971]
0.8567205734250669


In [5]:
import numpy as np

# 創建一個形狀為 (3, 4) 的數組
a = np.arange(2, 14).reshape((3, 4))
print(a)
print("\n")

# 返回數組中最小值的索引（扁平化的索引）
min_index = np.argmin(a)
print(min_index)
print("\n")

# 返回數組中最大值的索引（扁平化的索引）
max_index = np.argmax(a)
print(max_index)
print("\n")

# 計算數組 a 的平均值
mean_value = np.mean(a)
print(mean_value)
print("\n")

# 也可以使用數組對象的 mean 方法計算平均值
mean_value_alt = a.mean()
print(mean_value_alt)
print("\n")

# 使用 np.average 函數計算加權平均值（在本例中未指定權重，因此等同於平均值）
weighted_mean = np.average(a)
print(weighted_mean)
print("\n")

# 計算數組 a 的中位數
median_value = np.median(a)
print(median_value)
print("\n")

# 複製並輸出原始數組 a
print(a)
print("\n")

# 計算數組元素的累積和，然後重新塑形為 (3, 4)
cumulative_sum = np.cumsum(a).reshape((3, 4))
print(cumulative_sum)
print("\n")

# 計算相鄰元素的差值
difference = np.diff(a)
print(difference)
print("\n")

# 創建一個降序的數組 b，形狀為 (3, 4)
b = np.arange(14, 2, -1).reshape((3, 4))
print(b)
print("\n")

# 對數組 b 進行排序，按行進行升序排序
sorted_b = np.sort(b)
print(sorted_b)
print("\n")

# 使用 transpose 函數進行轉置（矩陣的行和列互換）
transposed_b = np.transpose(b)
print(transposed_b)
print("\n")

# 也可以使用數組對象的 T 屬性進行轉置
transposed_b_alt = b.T
print(transposed_b_alt)
print("\n")

# 矩陣相乘：b 的轉置乘以 b
dot_product = transposed_b.dot(b)
print(dot_product)
print("\n")

# 將數組 b 中小於 4 的元素設為 4，大於 10 的元素設為 10
clipped_b = np.clip(b, 4, 10)
print(clipped_b)
print("\n")

# 計算數組 b 沿著軸 1（列）的平均值
mean_along_axis1 = np.mean(b, axis=1)
print(mean_along_axis1)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


0


11


7.5


7.5


7.5


7.5


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


[[ 2  5  9 14]
 [20 27 35 44]
 [54 65 77 90]]


[[1 1 1]
 [1 1 1]
 [1 1 1]]


[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


[[10 10 10 10]
 [10  9  8  7]
 [ 6  5  4  4]]


[12.5  8.5  4.5]


In [6]:
import numpy as np

# 創建一維數組 a，範圍為 3 到 15（不包括 15）
a = np.arange(3, 15)
print("一維數組 a:")
print(a)

# 輸出索引為 3 的元素
print("索引為 3 的元素:", a[3])
print("\n")

# 創建二維數組 a，形狀為 (3, 4)，範圍為 3 到 15（不包括 15）
a = np.arange(3, 15).reshape(3, 4)
print("二維數組 a:")
print(a)

# 輸出索引為 2 的行
print("索引為 2 的行:", a[2])

# 輸出索引為 (1, 1) 的元素
print("索引為 (1, 1) 的元素:", a[1][1])
# 或者使用逗號分隔的索引
print("索引為 (1, 1) 的元素（另一種方法）:", a[1, 1])

# 輸出索引為 1 的整行
print("索引為 1 的整行:", a[1, :])

# 輸出索引為 1 的整列
print("索引為 1 的整列:", a[:, 1])

# 輸出索引為 1 的行中索引為 1 到 2 的元素
print("索引為 1 的行中索引為 1 到 2 的元素:", a[1, 1:3])
print("\n")

# 逐行迭代數組 a
print("逐行迭代:")
for row in a:
    print(row)
print("\n")

# 逐列迭代數組 a 的轉置
print("逐列迭代（轉置）:")
for column in a.T:
    print(column)
print("\n")

# 展平數組 a（轉為一維數組）
print("展平數組 a:")
print(a.flatten())
print("\n")

# 使用 flat 迭代數組 a 的每個元素
print("使用 flat 迭代元素:")
for element in a.flat:
    print(element)


一維數組 a:
[ 3  4  5  6  7  8  9 10 11 12 13 14]
索引為 3 的元素: 6


二維數組 a:
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
索引為 2 的行: [11 12 13 14]
索引為 (1, 1) 的元素: 8
索引為 (1, 1) 的元素（另一種方法）: 8
索引為 1 的整行: [ 7  8  9 10]
索引為 1 的整列: [ 4  8 12]
索引為 1 的行中索引為 1 到 2 的元素: [8 9]


逐行迭代:
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


逐列迭代（轉置）:
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


展平數組 a:
[ 3  4  5  6  7  8  9 10 11 12 13 14]


使用 flat 迭代元素:
3
4
5
6
7
8
9
10
11
12
13
14


In [7]:
import numpy as np

# 創建兩個一維數組 a 和 b
a = np.array([1, 1, 1])
b = np.array([2, 2, 2])

# 使用 vstack 將兩個數組垂直堆疊
vstack_result = np.vstack((a, b))
print("垂直堆疊數組 a 和 b:")
print(vstack_result)
print("\n")

# 將垂直堆疊的結果賦值給新的變數 c，並輸出數組形狀
c = vstack_result
print("數組形狀 - a:", a.shape, "b:", b.shape, "c:", c.shape)
print("\n")

# 使用 hstack 將兩個數組水平堆疊
hstack_result = np.hstack((a, b))
print("水平堆疊數組 a 和 b:")
print(hstack_result)
print("數組形狀 - a:", a.shape, "b:", b.shape, "c:", c.shape, "d:", hstack_result.shape)
print("\n")

# 將一維數組 a 轉為二維數組，形狀為 (3, 1)
a_2d = a[:, np.newaxis]
print("重塑 a（添加新軸）:")
print(a_2d)
print("\n")

# 將二維數組 a_2d 轉置（沿著新的軸）
a_transposed = a[np.newaxis, :]
print("轉置 a_2d（使用新軸）:")
print(a_transposed)
print("轉置後的 a_2d 形狀:", a_transposed.shape)
print("\n")

# 創建兩個二維數組 a 和 b，形狀均為 (3, 1)
a = np.array([1, 1, 1])[:, np.newaxis]
b = np.array([2, 2, 2])[:, np.newaxis]

# 使用 concatenate 在現有軸上連接兩個數組
concatenated_result = np.concatenate((a, b, b, a))
print("沿軸 0 連接的數組:")
print(concatenated_result)

# 使用 concatenate 在新的軸上連接兩個數組
concatenated_result_axis1 = np.concatenate((a, b, b, a), axis=1)
print("\n沿軸 1 連接的數組:")
print(concatenated_result_axis1)


垂直堆疊數組 a 和 b:
[[1 1 1]
 [2 2 2]]


數組形狀 - a: (3,) b: (3,) c: (2, 3)


水平堆疊數組 a 和 b:
[1 1 1 2 2 2]
數組形狀 - a: (3,) b: (3,) c: (2, 3) d: (6,)


重塑 a（添加新軸）:
[[1]
 [1]
 [1]]


轉置 a_2d（使用新軸）:
[[1 1 1]]
轉置後的 a_2d 形狀: (1, 3)


沿軸 0 連接的數組:
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]

沿軸 1 連接的數組:
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [8]:
import numpy as np

# 創建一個形狀為 (3, 4) 的數組
a = np.arange(12).reshape((3, 4))
print("原始數組 a:")
print(a)
print("\n")

# 使用 np.split 將數組 a 沿著水平方向（axis=1）分割成兩部分
split_horizontal = np.split(a, 2, axis=1)
print("沿著軸 1 將數組分割為 2 部分:")
print(split_horizontal)
print("\n")

# 使用 np.split 將數組 a 沿著垂直方向（axis=0）分割成三部分
split_vertical = np.split(a, 3, axis=0)
print("沿著軸 0 將數組分割為 3 部分:")
print(split_vertical)
print("\n")

# 使用 np.split 將數組 a 沿著水平方向（axis=1）分割成四部分
# 注意：必須能夠均勻分割
split_fail = np.split(a, 4, axis=1)  # 會引發錯誤
print("嘗試沿著軸 1 將數組分割為 4 部分（將引發錯誤）:")

# 使用 np.array_split 將數組 a 沿著水平方向（axis=1）不均勻分割成三部分
array_split_horizontal = np.array_split(a, 3, axis=1)
print("\n沒有均勻分割沿著軸 1 的數組，分為 3 部分:")
print(array_split_horizontal)
print("\n")

# 使用 np.vsplit 將數組 a 垂直分割成三部分
vsplit_result = np.vsplit(a, 3)
print("垂直分割數組為 3 部分:")
print(vsplit_result)
print("\n")

# 使用 np.hsplit 將數組 a 水平分割成兩部分
hsplit_result = np.hsplit(a, 2)
print("水平分割數組為 2 部分:")
print(hsplit_result)


原始數組 a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


沿著軸 1 將數組分割為 2 部分:
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


沿著軸 0 將數組分割為 3 部分:
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


嘗試沿著軸 1 將數組分割為 4 部分（將引發錯誤）:

沒有均勻分割沿著軸 1 的數組，分為 3 部分:
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


垂直分割數組為 3 部分:
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


水平分割數組為 2 部分:
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [9]:

# 創建一個一維數組 a，範圍為 0 到 3
a = np.arange(4)
print("原始數組 a:", a)

# 將變數 b 和 c 指向與 a 相同的數組對象
b = a
c = a

# 將變數 d 指向與 b 相同的數組對象
d = b

# 修改數組 a 中的元素，將索引為 0 的元素設置為 0.3
a[0] = 0.3
print("修改後的數組 a:", a)

# 再次修改數組 a 中的元素，將索引為 0 的元素設置為 11
a[0] = 11
print("再次修改後的數組 a:", a)
print("變數 b:", b)
print("變數 c:", c)
print("變數 d:", d)
print("\n")

# 修改變數 d 中的元素，將索引為 1 到 2 的元素設置為 22 和 33
d[1:3] = [22, 33]
print("修改變數 d 後的數組 a:", a)
print("變數 b:", b)
print("變數 c:", c)
print("變數 d:", d)
print("\n")

# 使用 copy() 方法複製數組 a，並賦值給變數 b
a = np.arange(4)
b = a.copy()
print("複製後的數組 a:", a)
print("複製後的數組 b:", b)

# 修改數組 a 中的元素，將索引為 3 的元素設置為 44
a[3] = 44
print("修改數組 a 後的數組 a:", a)
print("複製後的數組 b 不受影響:", b)



原始數組 a: [0 1 2 3]
修改後的數組 a: [0 1 2 3]
再次修改後的數組 a: [11  1  2  3]
變數 b: [11  1  2  3]
變數 c: [11  1  2  3]
變數 d: [11  1  2  3]


修改變數 d 後的數組 a: [11 22 33  3]
變數 b: [11 22 33  3]
變數 c: [11 22 33  3]
變數 d: [11 22 33  3]


複製後的數組 a: [0 1 2 3]
複製後的數組 b: [0 1 2 3]
修改數組 a 後的數組 a: [ 0  1  2 44]
複製後的數組 b 不受影響: [0 1 2 3]


In [10]:
import pandas as pd
import numpy as np

# 創建一個 Pandas Series
s = pd.Series([1, 2, 3, 4, 5, 6, np.nan, 44, 1])
print("Pandas Series:")
print(s)
print("\n")

# 生成日期範圍
dates = pd.date_range('20230101', periods=6)
print("日期範圍:")
print(dates)
print('\n')

# 創建一個 DataFrame，包含隨機數，行索引為日期，列索引為 'a', 'b', 'c', 'd'
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['a', 'b', 'c', 'd'])
print("DataFrame:")
print(df)
print('\n')

# 創建另一個 DataFrame，包含一個二維 NumPy 數組，並進行描述性統計
df1 = pd.DataFrame(np.arange(3, 15).reshape((3, 4)))
print("DataFrame from NumPy array:")
print(df1)
print("描述性統計:")
print(df1.describe())
print("轉置:")
print(df1.T)
print("按行索引降序排序:")
print(df1.sort_index(axis=0, ascending=False))
print('\n')

# 創建另一個 DataFrame，包含隨機數，行索引為日期，列索引為 'a', 'b', 'c', 'd'
df2 = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['a', 'b', 'c', 'd'])
print("另一個 DataFrame:")
print(df2)
print("數據類型:")
print(df2.dtypes)
print("行索引:")
print(df2.index)
print("列索引:")
print(df2.columns)
print("數據值:")
print(df2.values)
print('\n')
print("轉置:")
print(df2.T)
print('\n')
print("按列索引降序排序:")
print(df2.sort_index(axis=1, ascending=False))


Pandas Series:
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     NaN
7    44.0
8     1.0
dtype: float64


日期範圍:
DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')


DataFrame:
                   a         b         c         d
2023-01-01 -0.502935  0.076962  0.260923 -0.161913
2023-01-02  1.422202  1.892654 -0.123456  2.422337
2023-01-03 -0.255398 -0.777744  0.048887 -1.158168
2023-01-04  0.375672 -0.249625 -0.472211  1.364199
2023-01-05 -0.405253 -0.952170  0.011326  0.656681
2023-01-06 -1.539383 -1.155633 -0.823966 -0.797647


DataFrame from NumPy array:
    0   1   2   3
0   3   4   5   6
1   7   8   9  10
2  11  12  13  14
描述性統計:
          0     1     2     3
count   3.0   3.0   3.0   3.0
mean    7.0   8.0   9.0  10.0
std     4.0   4.0   4.0   4.0
min     3.0   4.0   5.0   6.0
25%     5.0   6.0   7.0   8.0
50%     7.0   8.0   9.0  10.0
75%     9.0  10.0  1

In [11]:
import pandas as pd
import numpy as np

# 生成日期範圍
dates = pd.date_range('20230101', periods=6)

# 創建 DataFrame，行索引為日期，列索引為 'A', 'B', 'C', 'D'
df = pd.DataFrame(np.arange(24).reshape((6, 4)), index=dates, columns=['A', 'B', 'C', 'D'])
print("DataFrame:")
print(df)
print("\n")

# 選擇 'A' 列的兩種方法
print("選擇 'A' 列:")
print(df['A'])
print("\n")
print(df.A)
print("\n")

# 選擇前三行
print("選擇前三行:")
print(df[0:3])
print("\n")

# 用行索引選擇特定行
print("用行索引選擇 '20230102' 行:")
print(df.loc['20230102'])
print("\n")

# 用行和列索引進行切片選擇
print("用行和列索引進行切片選擇:")
print(df.loc[:, ['A', 'B']])
print("\n")

# 同時選擇行和列
print("同時選擇 '20230102' 行的 'A', 'B' 列:")
print(df.loc['20230102', ['A', 'B']])
print("\n")

# 使用 iloc 進行位置索引
print("使用 iloc 選擇第三行:")
print(df.iloc[3])
print("\n")

# 使用 iloc 進行位置索引的切片選擇
print("使用 iloc 選擇第三到第五行的第二到第三列:")
print(df.iloc[3:5, 1:3])
print("\n")

# 使用 iloc 選擇不連續的行和列
print("使用 iloc 選擇第一、三、五行的第二到第三列:")
print(df.iloc[[1, 3, 5], 1:3])
print("\n")

# 原始 DataFrame
print("原始 DataFrame:")
print(df)
print("\n")

# 使用條件選擇
print("選擇 'A' 列中大於 8 的行:")
print(df[df.A > 8])


DataFrame:
             A   B   C   D
2023-01-01   0   1   2   3
2023-01-02   4   5   6   7
2023-01-03   8   9  10  11
2023-01-04  12  13  14  15
2023-01-05  16  17  18  19
2023-01-06  20  21  22  23


選擇 'A' 列:
2023-01-01     0
2023-01-02     4
2023-01-03     8
2023-01-04    12
2023-01-05    16
2023-01-06    20
Freq: D, Name: A, dtype: int64


2023-01-01     0
2023-01-02     4
2023-01-03     8
2023-01-04    12
2023-01-05    16
2023-01-06    20
Freq: D, Name: A, dtype: int64


選擇前三行:
            A  B   C   D
2023-01-01  0  1   2   3
2023-01-02  4  5   6   7
2023-01-03  8  9  10  11


用行索引選擇 '20230102' 行:
A    4
B    5
C    6
D    7
Name: 2023-01-02 00:00:00, dtype: int64


用行和列索引進行切片選擇:
             A   B
2023-01-01   0   1
2023-01-02   4   5
2023-01-03   8   9
2023-01-04  12  13
2023-01-05  16  17
2023-01-06  20  21


同時選擇 '20230102' 行的 'A', 'B' 列:
A    4
B    5
Name: 2023-01-02 00:00:00, dtype: int64


使用 iloc 選擇第三行:
A    12
B    13
C    14
D    15
Name: 2023-01-04 00:00:00, dtype: i

`iloc` 和 `loc` 是 Pandas 中用於選擇和索引 DataFrame 的兩種方法，主要差異在於索引的方式。

1. **iloc (Integer-location based indexing):**
   - 使用整數位置索引（從 0 開始），類似於 NumPy 的索引方式。
   - 通過位置選擇單個元素、切片、布爾索引等。

   ```python
   df.iloc[行位置, 列位置]
   ```

2. **loc (Label-based indexing):**
   - 使用標籤索引，即行或列的標籤名稱。
   - 通過標籤選擇單個元素、切片、布爾索引等。

   ```python
   df.loc[行標籤, 列標籤]
   ```

簡而言之，`iloc` 使用整數位置索引，而 `loc` 使用標籤索引。以下是一些示例：

```python
# 使用 iloc 選擇第二行第三列的值
df.iloc[1, 2]

# 使用 loc 選擇 '20230102' 行的 'C' 列的值
df.loc['20230102', 'C']
```

需要注意的是，`iloc` 使用的是 Python 風格的索引，即半開區間 `[start, stop)`，而 `loc` 使用的是標籤索引，即閉區間 `[start, stop]`。

In [12]:
import pandas as pd
import numpy as np

# 生成日期範圍
dates = pd.date_range('20230101', periods=6)

# 創建 DataFrame，行索引為日期，列索引為 'A', 'B', 'C', 'D'
df = pd.DataFrame(np.arange(24).reshape((6, 4)), index=dates, columns=['A', 'B', 'C', 'D'])
print("原始 DataFrame:")
print(df)
print("\n")

# 用 iloc 修改特定位置的值
df.iloc[2, 2] = 1111
print("用 iloc 修改特定位置的值:")
print(df)
print("\n")

# 用 loc 修改特定位置的值
df.loc['20230101', 'B'] = 2222
print("用 loc 修改特定位置的值:")
print(df)
print("\n")

# 用條件修改符合條件的值為 0
df[df.A > 4] = 0
print("將 'A' 列中大於 4 的值修改為 0:")
print(df)
print("\n")

# 將 'B' 列中對應 'A' 列中大於 4 的值修改為 0
df = pd.DataFrame(np.arange(24).reshape((6, 4)), index=dates, columns=['A', 'B', 'C', 'D'])
df.B[df.A > 4] = 0
print("將 'B' 列中對應 'A' 列中大於 4 的值修改為 0:")
print(df)
print("\n")

# 將 'A' 列中大於 4 的值修改為 0
df = pd.DataFrame(np.arange(24).reshape((6, 4)), index=dates, columns=['A', 'B', 'C', 'D'])
df.A[df.A > 4] = 0
print("將 'A' 列中大於 4 的值修改為 0:")
print(df)
print("\n")

# 新增一列 'F'，所有值為 NaN
df['F'] = np.nan
print("新增一列 'F'，所有值為 NaN:")
print(df)
print("\n")

# 新增一列 'E'，使用 pd.Series 進行賦值
df['E'] = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20230101', periods=6))
print("新增一列 'E'，使用 pd.Series 進行賦值:")
print(df)


原始 DataFrame:
             A   B   C   D
2023-01-01   0   1   2   3
2023-01-02   4   5   6   7
2023-01-03   8   9  10  11
2023-01-04  12  13  14  15
2023-01-05  16  17  18  19
2023-01-06  20  21  22  23


用 iloc 修改特定位置的值:
             A   B     C   D
2023-01-01   0   1     2   3
2023-01-02   4   5     6   7
2023-01-03   8   9  1111  11
2023-01-04  12  13    14  15
2023-01-05  16  17    18  19
2023-01-06  20  21    22  23


用 loc 修改特定位置的值:
             A     B     C   D
2023-01-01   0  2222     2   3
2023-01-02   4     5     6   7
2023-01-03   8     9  1111  11
2023-01-04  12    13    14  15
2023-01-05  16    17    18  19
2023-01-06  20    21    22  23


將 'A' 列中大於 4 的值修改為 0:
            A     B  C  D
2023-01-01  0  2222  2  3
2023-01-02  4     5  6  7
2023-01-03  0     0  0  0
2023-01-04  0     0  0  0
2023-01-05  0     0  0  0
2023-01-06  0     0  0  0


將 'B' 列中對應 'A' 列中大於 4 的值修改為 0:
             A  B   C   D
2023-01-01   0  1   2   3
2023-01-02   4  5   6   7
2023-01-03   8  0  10  

In [13]:
import pandas as pd
import numpy as np

# 生成日期範圍
dates = pd.date_range('20230101', periods=6)

# 創建 DataFrame，行索引為日期，列索引為 'A', 'B', 'C', 'D'
df = pd.DataFrame(np.arange(24).reshape((6, 4)), index=dates, columns=['A', 'B', 'C', 'D'])

# 將某些值設置為 NaN
df.iloc[0, 1] = np.nan
df.iloc[1, 2] = np.nan

print("原始 DataFrame:")
print(df)
print("\n")

# 使用 dropna() 刪除包含 NaN 值的行
print("刪除包含 NaN 值的行（任意值為 NaN 就刪除整行）:")
print(df.dropna(axis=0, how='any'))
print("\n")

# 使用 dropna() 刪除所有值均為 NaN 的行
print("刪除所有值均為 NaN 的行（所有值都為 NaN 才刪除整行）:")
print(df.dropna(axis=0, how='all'))
print("\n")

# 使用 fillna() 將 NaN 值填充為特定值（這裡是填充為 0）
print("將 NaN 值填充為 0:")
print(df.fillna(value=0))
print("\n")

# 使用 isnull() 檢查每個元素是否為 NaN
print("檢查每個元素是否為 NaN:")
print(df.isnull())
print("\n")

# 使用 np.any() 判斷是否存在任何 NaN 值
print("判斷是否存在任何 NaN 值:")
print(np.any(df.isnull()) == True)



原始 DataFrame:
             A     B     C   D
2023-01-01   0   NaN   2.0   3
2023-01-02   4   5.0   NaN   7
2023-01-03   8   9.0  10.0  11
2023-01-04  12  13.0  14.0  15
2023-01-05  16  17.0  18.0  19
2023-01-06  20  21.0  22.0  23


刪除包含 NaN 值的行（任意值為 NaN 就刪除整行）:
             A     B     C   D
2023-01-03   8   9.0  10.0  11
2023-01-04  12  13.0  14.0  15
2023-01-05  16  17.0  18.0  19
2023-01-06  20  21.0  22.0  23


刪除所有值均為 NaN 的行（所有值都為 NaN 才刪除整行）:
             A     B     C   D
2023-01-01   0   NaN   2.0   3
2023-01-02   4   5.0   NaN   7
2023-01-03   8   9.0  10.0  11
2023-01-04  12  13.0  14.0  15
2023-01-05  16  17.0  18.0  19
2023-01-06  20  21.0  22.0  23


將 NaN 值填充為 0:
             A     B     C   D
2023-01-01   0   0.0   2.0   3
2023-01-02   4   5.0   0.0   7
2023-01-03   8   9.0  10.0  11
2023-01-04  12  13.0  14.0  15
2023-01-05  16  17.0  18.0  19
2023-01-06  20  21.0  22.0  23


檢查每個元素是否為 NaN:
                A      B      C      D
2023-01-01  False   True  False  False
20

In [14]:
from google.colab import files
# 上傳csv檔案
uploaded = files.upload()

Saving 找出銷售王.xlsx to 找出銷售王.xlsx
