<a href="https://colab.research.google.com/github/chenboju/Python/blob/numpy/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
import numpy as np

# 創建一個二維 NumPy 數組
arr = np.array([[1, 2, 3], [2, 3, 4]])

# 輸出數組
print(arr)

# 輸出數組的維度數量
print('number of dim', arr.ndim)

# 輸出數組的形狀（每個維度的大小）
print('shape', arr.shape)

# 輸出數組中元素的總數
print('size', arr.size)


[[1 2 3]
 [2 3 4]]
number of dim 2
shape (2, 3)
size 6


In [31]:
import numpy as np

# 創建一個 NumPy 數組，指定數據類型為32位整數
a = np.array([2, 34, 6, 7, 8], dtype=np.int32)
print(a)
# 輸出數組的數據類型
print(a.dtype)

# 創建一個 NumPy 數組，指定數據類型為64位浮點數
a = np.array([2, 34, 6, 7, 8], dtype=np.float64)
print(a)
# 輸出數組的數據類型
print(a.dtype)
print("\n")

# 創建一個二維 NumPy 數組
b = np.array([[2, 3, 4, 5], [5, 6, 7, 8]])
print(b)
print("\n")

# 創建一個三行四列的零矩陣
c = np.zeros((3, 4))
print(c)
print("\n")

# 創建一個三行四列的元素全為1的矩陣，指定數據類型為16位整數
d = np.ones((3, 4), dtype=np.int16)
print(d)
print("\n")

# 創建一個從2開始，以步長5生成的一維數組
e = np.arange(2, 50, 5)
print(e)
print("\n")

# 創建一個從0到11的數組，並將其形狀改為三行四列
e = np.arange(12).reshape((3, 4))
print(e)

# 生成一個從1到10的等差序列，共包含5個數字
f = np.linspace(1, 10, 5)
print(f)

# 生成一個從1到20的等差序列，共包含10個數字，並將其形狀改為兩行五列
f = np.linspace(1, 20, 10).reshape((2, 5))
print(f)


[ 2 34  6  7  8]
int32
[ 2. 34.  6.  7.  8.]
float64


[[2 3 4 5]
 [5 6 7 8]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[ 2  7 12 17 22 27 32 37 42 47]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.    3.25  5.5   7.75 10.  ]
[[ 1.          3.11111111  5.22222222  7.33333333  9.44444444]
 [11.55555556 13.66666667 15.77777778 17.88888889 20.        ]]


In [27]:
import numpy as np

# 創建一維數組 a 和一維數組 b
a = np.array([10, 20, 30, 40])
b = np.arange(4)

# 輸出數組 a 和數組 b
print(a, b)

# 對應元素相減
c = a - b
print(c)

# 對應元素的指數運算
c = a ** b
print(c)

# 對數組 a 中的每個元素進行 sin 運算，並乘以 10
c = 10 * np.sin(a)
print(c)

# 輸出數組 b、滿足條件的布林數組（b<3 和 b==3）
print(b, b < 3, b == 3)

# 創建二維數組 a 和二維數組 b
a = np.array([[1, 1], [0, 1]])
b = np.arange(4).reshape((2, 2))

# 輸出數組 a 和數組 b
print(a)
print("\n")
print(b)
print("\n")

# 對應元素相乘
c = a * b
# 矩陣乘法
c_dot = np.dot(a, b)
print(c)
print("\n")
print(c_dot)

# 創建一個形狀為 (2, 4) 的隨機數組
a = np.random.random((2, 4))

# 輸出數組 a、按行求和、按列求最小值、全局求最大值
print(a)
print(np.sum(a, axis=1)) #axis=1，按行
print(np.min(a, axis=0))  #axis=0，按列
print(np.max(a))


[10 20 30 40] [0 1 2 3]
[10 19 28 37]
[    1    20   900 64000]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[0 1 2 3] [ True  True  True False] [False False False  True]
[[1 1]
 [0 1]]


[[0 1]
 [2 3]]


[[0 1]
 [0 3]]


[[2 4]
 [2 3]]
[[0.40919906 0.27956493 0.35650053 0.24244995]
 [0.16943461 0.73036549 0.57294525 0.90577907]]
[1.28771447 2.37852442]
[0.16943461 0.27956493 0.35650053 0.24244995]
0.9057790661724524


In [49]:
import numpy as np

# 創建一個形狀為 (3, 4) 的數組
a = np.arange(2, 14).reshape((3, 4))
print(a)
print("\n")

# 返回數組中最小值的索引（扁平化的索引）
min_index = np.argmin(a)
print(min_index)
print("\n")

# 返回數組中最大值的索引（扁平化的索引）
max_index = np.argmax(a)
print(max_index)
print("\n")

# 計算數組 a 的平均值
mean_value = np.mean(a)
print(mean_value)
print("\n")

# 也可以使用數組對象的 mean 方法計算平均值
mean_value_alt = a.mean()
print(mean_value_alt)
print("\n")

# 使用 np.average 函數計算加權平均值（在本例中未指定權重，因此等同於平均值）
weighted_mean = np.average(a)
print(weighted_mean)
print("\n")

# 計算數組 a 的中位數
median_value = np.median(a)
print(median_value)
print("\n")

# 複製並輸出原始數組 a
print(a)
print("\n")

# 計算數組元素的累積和，然後重新塑形為 (3, 4)
cumulative_sum = np.cumsum(a).reshape((3, 4))
print(cumulative_sum)
print("\n")

# 計算相鄰元素的差值
difference = np.diff(a)
print(difference)
print("\n")

# 創建一個降序的數組 b，形狀為 (3, 4)
b = np.arange(14, 2, -1).reshape((3, 4))
print(b)
print("\n")

# 對數組 b 進行排序，按行進行升序排序
sorted_b = np.sort(b)
print(sorted_b)
print("\n")

# 使用 transpose 函數進行轉置（矩陣的行和列互換）
transposed_b = np.transpose(b)
print(transposed_b)
print("\n")

# 也可以使用數組對象的 T 屬性進行轉置
transposed_b_alt = b.T
print(transposed_b_alt)
print("\n")

# 矩陣相乘：b 的轉置乘以 b
dot_product = transposed_b.dot(b)
print(dot_product)
print("\n")

# 將數組 b 中小於 4 的元素設為 4，大於 10 的元素設為 10
clipped_b = np.clip(b, 4, 10)
print(clipped_b)
print("\n")

# 計算數組 b 沿著軸 1（列）的平均值
mean_along_axis1 = np.mean(b, axis=1)
print(mean_along_axis1)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


0


11


7.5


7.5


7.5


7.5


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


[[ 2  5  9 14]
 [20 27 35 44]
 [54 65 77 90]]


[[1 1 1]
 [1 1 1]
 [1 1 1]]


[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


[[10 10 10 10]
 [10  9  8  7]
 [ 6  5  4  4]]


[12.5  8.5  4.5]
